### PR TITLE
Remove unnecessary AspNetCore dependency for net461

### PR DESCRIPTION
**Pull request by dustinsoftware**
Experimental attempt at making #68 better.

### CODE REVIEW

**Comment by JeremyTCD** [comment]
This looks good too! Do people use [Microsoft.AspNetCore.Hosting](https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting/) from netfx projects though? E.g net461 console application using `WebHostBuilder` manually. Will have to do some reading before deciding on this.

**Comment by dustinsoftware** [comment]
Yeah you are correct, it's still supported to use `.NET Core 2.1` on netfx... 

This PR seems like a simpler path and we could say this use case is unsupported with netfx given the (hopefully?) small customer base using ASP.NET Core 2.1 on netfx.

Alternatively, we could support ASP.NET Core + netfx _as well as_ classic ASP.NET MVC without the package bloat by creating an optional `Javascript.NodeJS.Middleware` package that can be added in addition to `Javascript.NodeJS`. React.NET takes that approach ([example](https://github.com/reactjs/React.NET/blob/master/src/React.AspNet.Middleware/ReactBuilderExtensions.cs)). As an aside, this approach would also allow the DI system to be injected by the host instead of requiring consumers to use `Microsoft.Extensions.DependencyInjection`, which appears to be used for primarily [singletons](https://github.com/JeringTech/Javascript.NodeJS/blob/2cd5d66a23746de7563ed71872847db89a9f078d/src/NodeJS/NodeJSServiceCollectionExtensions.cs#L30-L36)...

**Comment by JeremyTCD** [comment]
I appreciate your effort on this PR but as is I've decided not to merge it.  

Correct me if I'm wrong, the trade-off seems to be between

- breaking backward compatibility (this'll happen in both cases - if we drop ASP.NET Core for netfx or if we extract a Middleware package) and 
- reducing dependencies (which'll help avoid netfx binding redirect issues).

To be honest, I'm not convinced that reducing dependencies is worth breaking backward compatibility.  Am open to arguments on why reducing dependencies might outweigh breaking backward compatibility for netfx, perhaps I'm not fully aware of the downsides from a larger dependency graph.

-----

I think there is also a difference in how we use dependency injection (DI). I use it for [extensibility](https://github.com/JeringTech/Javascript.NodeJS#extensibility) in open source projects. E.g if a user who needs to serialize/deserialize special types can overwrite `IJsonService`:

``` csharp
var services = new ServiceCollection();
services.AddNodeJS();

// Overwrite the default DI service
services.AddSingleton<IJsonService, MyJsonService>();

ServiceProvider serviceProvider = services.BuildServiceProvider();
INodeJSService nodeJSService = serviceProvider.GetRequiredService<INodeJSService>();
```

Extensibility means less work maintaining the library - users can add small modifications on their own - and convenience for users - they don't need to create pull requests to add simple features.  

I use DI extensively in tests for easy mocking of dependencies. I prefer "pure" unit tests in open source projects because I know my interaction with the library will be intermittent, i.e work on it for a week or two then not touch it for a month. This way when I do come back to make quick changes like bug fixes I can merge with confidence as long as tests pass.  

Removing DI isn't something I'd consider for this library. Removal of `Hosting.Abstractions` for netfx looked promising but since ASP.NET Core is usable from netfx I think it isn't worth it.

**Comment by dustinsoftware** [comment]
Ok

**Pull request closed without merging**
