### PR TITLE
Add Module Reloading On File Change

### PR DESCRIPTION
**Pull request by JeremyTCD**
Details: https://github.com/JeringTech/Javascript.NodeJS/pull/69#issuecomment-583732296

### CODE REVIEW

**Comment by rosslovas** [comment]
>Come to think of it, restarting the server does nothing to in-memory stuff like previously loaded modules. We should just clear the NodeJS module cache (preserving NodeJS core modules like fs, path etc) on file change. This would be an instant clean reset for NodeJS.

This was my first idea but it was not an option for us because we have other `fs.watch` calls set up to accommodate for changing config files. In my code snippet in #67, when I clear `require.cache` instead of `process.exit(0)`, after a while of normal usage in which I change my js files a few times, if I change the aforementioned config file once, the log shows that many `fs.watch` calls are still active, one for each time the module that sets them up was reloaded:

```
[09:52:47 INF Jering.Javascript.NodeJS.HttpNodeJSService] Removing cached settings as file changed
[09:52:47 INF Jering.Javascript.NodeJS.HttpNodeJSService] Removing cached settings as file changed
[09:52:47 INF Jering.Javascript.NodeJS.HttpNodeJSService] Removing cached settings as file changed
[09:52:47 INF Jering.Javascript.NodeJS.HttpNodeJSService] Removing cached settings as file changed
[09:52:47 INF Jering.Javascript.NodeJS.HttpNodeJSService] Removing cached settings as file changed
...
```

While the old module instances themselves should have been garbage collected, unfortunately it seems not everything gets cleaned up.

**Comment by JeremyTCD** [comment]
That's interesting. What if we [force garbage collection](https://stackoverflow.com/questions/27321997/how-to-request-the-garbage-collector-in-node-js-to-run) after clearing the cache?

**Comment by JeremyTCD** [comment]
Scratch that, I think the problem is that [HttpServer.ts](https://github.com/JeringTech/Javascript.NodeJS/blob/Add_File_Watching/src/NodeJS/Javascript/Servers/OutOfProcess/Http/HttpServer.ts) has a reference to the fs module export (along with some other built in module exports). Will have to invalidate all those references.

**Comment by rosslovas** [comment]
Can confirm forcing garbage collection doesn't help.

A simpler way to demonstrate the problem is with `setInterval` e.g. a module with the following:

```ts
const now = Date.now();
setInterval(() => console.log(now), 5000);
```

It should only be possible to have one of those running at once, but clearing the module cache and reloading the module allows more and more to build up. There are probably plenty of other async operations that will cause the same problem.

Perhaps it's possible to track all async handles with [`async_hooks`](https://nodejs.org/api/async_hooks.html) and destroy them all when you clear the module cache? I wonder if that covers everything...

**Comment by JeremyTCD** [comment]
Ah okay, so the NodeJS runtime keeps direct references to callback methods and continues to call them when events trigger.

> async_hooks

This is interesting. Read through quickly and it looks like we can't manually destroy `AsyncResource`s though. Agreed, cleanly clearing all async-resources seems difficult. 

> I wonder if that covers everything...

Yeah, high risk of memory leaks.  

We'll have to take a look at NodeJS' source code and perhaps do some memory profiling to figure out if we can reload modules cleanly.  

If it isn't possible we'll just restart the process. Will have to figure out how to handle queued invocations that get canceled in that case. Am not satisfied with the current reliance on retries.

**Comment by JeremyTCD** [comment]
## Module Reloading Approaches
At present, users can use NodeJS's fs to watch files and restart the process when they change, thereby reloading all modules. While this works, module reloading is more popular than expected, so we should provide an out-of-the-box solution. Two possibilities:

### Delete Cached Modules
Delete modules from [require.cache](https://nodejs.org/api/modules.html#modules_require_cache) so they're reloaded:
> By deleting a key value from this object, the next require will reload the module.

#### Pros
Fast. Avoids restarting the process, avoids terminating invocations midway through.

#### Cons
Memory leaks. Even if we delete a module from the cache, as pointed out by @rosslovas, the NodeJS runtime may hold references to the module. This is typically due to async stuff - the runtime holds references to callbacks, which in turn hold references to the modules that created them.

Did a quick check to see if NodeJS exposes the structures holding callbacks. Found several cases where it doesn't. E.g if you call `setTimeout(callback, 100)`, an *internal* linked list `L` in [internal/timers.js](https://github.com/nodejs/node/blob/master/lib/internal/timers.js) holds [the callback](https://github.com/nodejs/node/blob/8a14884babdcfaaf0571c95830b3e7478c18afdb/lib/internal/timers.js#L359). It's inaccessible.

#### How we can make this work
When we need to reload a module, we can call a custom method, e.g `cleanup`. Users would define their modules as follows:

``` js
module.exports = {
    doSomething: (callback) => {
        ... // Do something
        callback(null, result);
    },
    cleanup: () => {
        ... // Cleanup async stuff, e.g clearTimeout()
    }
}
```

HttpServer.ts would have the following logic:

``` js
fs.watch(watchDirectory, { recursive: watchRecursive }, (_, filename) => {
    var moduleID = ... // We can easily tell from within NodeJS if the changed file is a loaded module, its ID is just its absolute file path
    var module = require.cache[moduleID];
    if (typeof module.cleanup === 'function') {
        module.cleanup(); // Cleanup async stuff
    }
    delete require.cache[moduleID];
    ... // Optionally cleanup and delete its dependencies
});
```

As noted in the comments, we can easily tell if a .js file that changes is a loaded module, and automatically reload it. Users will have to associate other kinds of files with modules to reload though, e.g if x.html changes, reload module x.js.

Users who aren't using async stuff or are just using one-off callbacks like setTimeout might not need 
to define `cleanup`. They have to be vigilant about libraries they depend on though, and also other situations apart from async where the runtime may hold on to references.

### Restart Process

#### Pros
Easy to implement. User's don't need to worry about memory leaks.

#### Cons
Slow. Restarting the process takes several hundred ms. We could start a new process while the previous one is cleaning up. If a user changes files rapidly this could cause a bunch of NodeJS processes.  

Unstable. If we kill the process immediately after file change, invocations terminate midway through. Users have to be wary of this. Also, when an invocation fails from a restart, the error is a generic `SocketError` so our logic has to use up a retry. If a user changes files often, all of an invocation's retries will be used up due to restarts.  

We could allow the previous process to complete while sending new requests to a new process. Again, if a user changes files rapidly this could cause a bunch of NodeJS processes.

### Conclusion

**Comment by dustinsoftware** [comment]
Since this is userland code, restarting the process seems like the simpler of the two options. You are correct that if any modules leak event listeners that there won't be a reliable way to detect them. There also could be child processes that are spawned (child_process.spawn), which should be cleaned up.

**Comment by JeremyTCD** [comment]
@dustinsoftware Yeah agreed, slightly quicker module reloads aren't worth the extra complexity. I've implemented process restarting on file change, just got to clean up, test and document.

**Comment by JeremyTCD** [comment]
🚀 5.4.0 released with file watching.

-----

## Enabling file watching:
``` csharp
services.Configure<OutOfProcessNodeJSOptions>(options => options.EnableFileWatching = true);
```
 ([more info on configuring options](https://github.com/JeringTech/Javascript.NodeJS#configuring-inodejsservice))

## More file watching options

[OutOfProcessNodeJSOptions](https://github.com/JeringTech/Javascript.NodeJS#outofprocessnodejsserviceoptions) (WatchPath, WatchSubdirectories, WatchFileNamePatterns, WatchGracefulShutdown).

## Benchmarks
- [NodeJS restart](https://github.com/JeringTech/Javascript.NodeJS#file-watching)
- [Effect on latency](https://github.com/JeringTech/Javascript.NodeJS#latency) (INodeJSService_Latency_InvokeFromFile_GracefulShutdownEnabled)

**Comment by dustinsoftware** [comment]
This is great!! Thanks for shipping it.

**Pull request merged**
